title: Te koop
#description: Gerenoveerde ééngezinswoning vlakbij het Moorkensplein
description: Sergeyselsstraat 27, 2140 Borgerhout
show_downloads: false
#google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: false
